/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzjz_Base64 */

#ifndef _Included_com_zzjz_Base64
#define _Included_com_zzjz_Base64
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzjz_Base64
 * Method:    encode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zzjz_Base64_encode
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_zzjz_Base64
 * Method:    decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zzjz_Base64_decode
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
